### PR TITLE
Validation and Rspec tests

### PR DESCRIPTION
**Pull request by petushka1**
# Validation and Tests
### Validate attributes. Test custom methods and validations

- [x] add validation to user and post models
- [x] install rspec
- [x] install ffi
- [x] add tests to check the validation
- [x] add tests for all custom models methods     
- [x] check and fix linters errors

### CODE REVIEW

**Review by DammyShittu — COMMENTED** [review]
Hi @petushka1,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### I am unable to successfully set up your project locally. When I run `rails db:migrate` I get these errors in the image. This is likely because you created the Likes table before creating the Posts table. Now because the Likes table references a non-existent posts table (at the time its migration is being run) it throws errors. Kindly fix that. You can consider deleting the likes table migration and generating a new one so that by the time it is run all needed data for it has been generated

  likes

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by petushka1** [comment]
image

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @petushka1, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Your migrations fail after running `rails db:migrate` command. Kindly fix those errors so that we can be able to review your project.

image

Notice:
To ensure that your migrations work as expected, I recommend deleting the `schema.rb` file, and then running `rails db: reset`. After that, run `rails db:migrate`. If the migrations do not show any errors, that's fine, you may request a new review. But if the migrations show errors, try to solve those errors and repeat the steps.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by petushka1** [comment]
- [x] rename migrations
- [x] remove schema.rb
- [x] drop db
- [x] db create
- [x] run migrations

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Nadia,  

Your project is complete, great job 🥇 There is nothing else to say other than... it's time to merge it 🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Model validations properly implemented
- Good Rspec unit test coverage

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**You can also consider:**
- Kindly add instructions in your ReadMe under the _Getting Started_ section, how to run the test cases of your project.
- I think you should change the header title _Authors_ to _Author_ in your ReadMe, as this project is worked on by a sole contributor. 
Implementing the above change(s) will make your ReadMe appear more professional.

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
